pipeline {
    agent any
    
    tools {
        nodejs 'nodejs-10'
    }

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main', changelog: false, poll: false, url: 'https://github.com/jaiswaladi246/NodeJS_WebApp_Public.git'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                sh "npm install"
            }
        }
        
        stage('Owasp Check') {
            steps {
                dependencyCheck additionalArguments: ' --scan ./ ', odcInstallation: 'D-Check'
                    dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
            }
        }
        
        stage('Docker build') {
            steps {
                withDockerRegistry(credentialsId: 'docker', url: 'https://index.docker.io/v1/') {
                    sh 'docker build -t nodeapp .'
                    sh 'docker tag demonodejs wamah/nodeapp:v1'
                 }
            }
        }
        
        stage('Docker Push') {
            steps {
                withDockerRegistry(credentialsId: 'docker', url: 'https://index.docker.io/v1/') {
                    sh 'docker push wamah/nodeapp:v1'
                 }
            }
        }
        
        stage('Docker deploy') {
            steps {
                withDockerRegistry(credentialsId: 'docker', url: 'https://index.docker.io/v1/') {
                    sh 'docker run -d --name demonodejs -p 8081:8081 wamah/nodeapp:v1 '
                }
            }
        }
    }
}

